// Image Service
function handleRemoveBackground() {
    const fileInput = document.getElementById('image-upload');
    const imageResult = document.getElementById('image-result');
    
    if (!fileInput.files || fileInput.files.length === 0) {
        alert('Please select an image first!');
        return;
    }
    
    const file = fileInput.files[0];
    
    // Show processing
    imageResult.innerHTML = `<div style="text-align: center; padding: 2rem;">
        Removing background... <i class="fas fa-spinner fa-spin"></i>
    </div>`;
    
    // Simulate background removal
    setTimeout(() => {
        const imageUrl = URL.createObjectURL(file);
        
        imageResult.innerHTML = `
            <h4>Background Removal Complete!</h4>
            <div style="display: flex; gap: 1rem; margin-top: 1rem; flex-wrap: wrap;">
                <div>
                    <h5>Original</h5>
                    <img src="${imageUrl}" style="max-width: 300px; border-radius: 5px;">
                </div>
                <div>
                    <h5>Background Removed</h5>
                    <div style="width: 300px; height: 300px; background: linear-gradient(45deg, #667eea 0%, #764ba2 100%); display: flex; align-items: center; justify-content: center; border-radius: 5px;">
                        <i class="fas fa-check-circle" style="font-size: 3rem; color: white;"></i>
                    </div>
                </div>
            </div>
            <div style="margin-top: 1rem;">
                <button class="btn btn-primary">
                    <i class="fas fa-download"></i> Download Processed Image
                </button>
            </div>
            <p style="margin-top: 1rem; color: var(--text-muted); font-size: 0.9rem;">
                <i class="fas fa-info-circle"></i> AI-powered background removal by OpenRouter
            </p>
        `;
    }, 2500);
}

function handleGenerateImage() {
    const prompt = document.getElementById('image-prompt').value;
    const generatedImage = document.getElementById('generated-image');
    
    if (!prompt.trim()) {
        alert('Please enter an image prompt!');
        return;
    }
    
    // Show processing
    generatedImage.innerHTML = `<div style="text-align: center; padding: 2rem;">
        Generating image with AI... <i class="fas fa-spinner fa-spin"></i>
        <p>Prompt: "${prompt}"</p>
    </div>`;
    
    // Simulate AI image generation
    setTimeout(() => {
        // Placeholder image based on prompt
        const imagePlaceholders = [
            'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w-400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=400&fit=crop',
            'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=400&fit=crop'
        ];
        
        const randomImage = imagePlaceholders[Math.floor(Math.random() * imagePlaceholders.length)];
        
        generatedImage.innerHTML = `
            <h4>AI Generated Image</h4>
            <p>Based on prompt: "${prompt}"</p>
            <div style="margin-top: 1rem;">
                <img src="${randomImage}" style="max-width: 400px; border-radius: 5px; border: 2px solid var(--accent);">
            </div>
            <div style="margin-top: 1rem; display: flex; gap: 1rem;">
                <button class="btn btn-primary">
                    <i class="fas fa-download"></i> Download Image
                </button>
                <button class="btn btn-outline">
                    <i class="fas fa-sync"></i> Generate Another
                </button>
            </div>
            <p style="margin-top: 1rem; color: var(--text-muted); font-size: 0.9rem;">
                <i class="fas fa-info-circle"></i> Generated by OpenRouter AI Image Model
            </p>
        `;
    }, 3000);
}